spring:
  application:
    name: later
  main:
    banner-mode: OFF
  datasource:
    url: jdbc:postgresql://localhost:5432/shareIt
    username: dbuser
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate.jdbc.time_zone: UTC
